replicaCount: 3

image:
  repository: chaabane10/mern-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

env:
  MONGO_URI: "mongodb://root:root@mongodb:27017"
  PORT: "4000"

ingress:
  enabled: false

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80